services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "11434:11434"  # Expose Ollama port
    volumes:
      - ./backend:/app
      - ollama_data:/root/.ollama  # Persist Ollama models
    environment:
      - FLASK_ENV=development
    working_dir: /app
    command: /app/start.sh

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  ollama_data:  # Define the volume for Ollama models